### ISSUE TITLE
todo: Tasks Lists

### ISSUE THREAD

**Issue by Klairm** [Klairm/flutter-spotify-downloader#3]
# Features
- [ ] Show download progress in a notification so user can leave the app running in the background
- [x] Show cover art in the track list 
- [ ] Multithread download ( is that even possible with Flutter? ) 
- [ ] Implement Intents to get playlists with the share button in Spotify 
- [ ] Handle errors displaying info about them

**Comment by Klairm** [comment]
Cover art done in 4b3bb1f6b638a4d2aaa7ecf9ae8e62424b249d24
